### ISSUE TITLE
Is this a ga4 nodejs client?

### ISSUE THREAD

**Issue by softmarshmallow** [googleapis/nodejs-analytics-data#107]
Not quite sure this is the right place to ask. but coulnt find any other place.
I'm curious if this is the implementation of https://developers.google.com/analytics/devguides/collection/protocol/ga4/

If so, simple Event example will be nice to have. (not report)

**Comment by LindaLawton** [comment]
No this library will help you extract data from Google analytics ga4 accounts it does not send data to it.

**Comment by sofisl** [comment]
Hi there! We are migrating this repo to googleapis/google-cloud-node. If this issue still persists, please reopen over there. Thank you!
