### ISSUE TITLE
What is the value of the "eventValue"?

### ISSUE THREAD

**Issue by alex-r89** [googleapis/nodejs-analytics-data#177]
Hi there, 

I am currently using this package to try and get how many page views each route on my site gets. I am doing this in the following way:

```js
  const analyticsDataClient = new BetaAnalyticsDataClient(OPTIONS)

  const runReport = async () => {
    const [response] = await analyticsDataClient.runReport({
      property: `properties/${propertyId}`,
      dateRanges: [
        {
          startDate: '7daysAgo',
          endDate: 'today'
        }
      ],
      dimensions: [{ name: 'pagePath' }],
      metrics: [{ name: 'eventCount' }],
      pageSize: 1
    })

    console.log('Report result:')
    response.rows.forEach((row) => {
      console.log(row.dimensionValues[0], row.metricValues[0])
    })
  }

```

The console log I see for the above is as follows:

```js
Report result:
{ value: '/someRoute', oneValue: 'value' } { value: '187', oneValue: 'value' }
{ value: '/someOtherRoute', oneValue: 'value' } { value: '12', oneValue: 'value' }
{ value: '/', oneValue: 'value' } { value: '242', oneValue: 'value' }
...more values here
```

Im not even sure if my `dimensions` or `metrics` values above are correct, they are complete guesses in regards to my goal of trying to get page view counts.

I am wondering though, what is the `value` here? Is this the number of page views this route has seen? There doesn't seem to be much explanation as to what this actually is.

Thanks

**Comment by sofisl** [comment]
Hi there! We are migrating this repo to googleapis/google-cloud-node. If this issue still persists, please reopen over there. Thank you!
