### ISSUE TITLE
ReadMe and sample should define GOOGLE_APPLICATION_CREDENTIALS 

### ISSUE THREAD

**Issue by LindaLawton** [googleapis/nodejs-analytics-data#187]
Currently there is nothing in this library which tells your users what GOOGLE_APPLICATION_CREDENTIALS  is and where to get it.

This should be documented here currently it is only documented in [Google cloud node.js client](https://github.com/googleapis/google-cloud-node) and [quickstart-client-libraries](https://developers.google.com/analytics/devguides/reporting/data/v1/quickstart-client-libraries#step_3_configure_authentication)

**Comment by ikuleshov** [comment]
Linda, I believe this sample addresses this question.
https://github.com/googleapis/nodejs-analytics-data/blob/c458a157bdc6893c9f86335b931e78f883506016/samples/quickstart_json_credentials.js#L52

**Comment by umang350** [comment]
Also, the documentation should show how you can pass the JSON data directly as a parameter to the constructor instead of JSON file path.

**Comment by sofisl** [comment]
Hi there! We are migrating this repo to googleapis/google-cloud-node. If this issue still persists, please reopen over there. Thank you!
