### ISSUE TITLE
Please add runFunnelReport  function

### ISSUE THREAD

**Issue by jayy-21** [googleapis/nodejs-analytics-data#215]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**
 **Describe the solution you'd like**
 **Describe alternatives you've considered**
 **Additional context**

**Comment by sofisl** [comment]
Hi there! We are migrating this repo to googleapis/google-cloud-node. If this issue still persists, please reopen over there. Thank you!
