### ISSUE TITLE
Trying to import google analytics

### ISSUE THREAD

**Issue by Jelbert** [googleapis/nodejs-analytics-data#220]
Thanks for stopping by to ask us a question! Please make sure to include:
- What you're trying to do
I'm trying to import @google-analytics/data

- What code you've already tried
![image](https://user-images.githubusercontent.com/5991069/176815867-e65af6e9-173e-4c47-8f32-65afbc2e8b41.png)

- Any error messages you're getting
![image](https://user-images.githubusercontent.com/5991069/176816016-5625c189-7265-4df6-aca1-db14ed71039f.png)

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

**Comment by umang350** [comment]
Please give more information and more part of code, try installing with NPM again and running the application again.

**Comment by sofisl** [comment]
Hi there! We are migrating this repo to googleapis/google-cloud-node. If this issue still persists, please reopen over there. Thank you!
