### ISSUE TITLE
keyFileJson instead of keyFilename

### ISSUE THREAD

**Issue by Suryalg** [googleapis/nodejs-analytics-data#224]
// Explicitly use service account credentials by specifying
  // the private key file.
  const analyticsDataClient = new BetaAnalyticsDataClient({
      keyFilename: credentialsJsonPath,
  });

can I give JSON content of the keyfile here somehow, that will be great for me

**Comment by umang350** [comment]
You can by passing the credential option in the constructor with the JSON data.

**Comment by sofisl** [comment]
Hi there! We are migrating this repo to googleapis/google-cloud-node. If this issue still persists, please reopen over there. Thank you!
