### ISSUE TITLE
Oauth2 support

### ISSUE THREAD

**Issue by LindaLawton** [googleapis/nodejs-analytics-data#41]
The only sample you appear to have works with service accounts.   Does this library also support normal Oauth2 authentication or just service account authentication? 

I tried setting the GOOGLE_APPLICATION_CREDENTIALS to a normal Oauth2 cred file and i get the following error message.

```
(node:14561) UnhandledPromiseRejectionWarning: Error: The incoming JSON object does not contain a client_email field
    at JWT.fromJSON (/home/linda/WebstormProjects/google_nodejs_samples/node_modules/google-gax/node_modules/google-auth-library/build/src/auth/jwtclient.js:195:19)
    at GoogleAuth._cacheClientFromJSON (/home/linda/WebstormProjects/google_nodejs_samples/node_modules/google-gax/node_modules/google-auth-library/build/src/auth/googleauth.js:301:16)
    at ReadStream.<anonymous> (/home/linda/WebstormProjects/google_nodejs_samples/node_modules/google-gax/node_modules/google-auth-library/build/src/auth/googleauth.js:335:36)
    at ReadStream.emit (events.js:228:7)
    at endReadableNT (_stream_readable.js:1185:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)

```

**Comment by guillaumeprevost** [comment]
After a while managed made it work using a "hybrid" approach to authentication with OAuth2.
 1. Client-side : prompt user to authenticate and authorize the app with given scopes
 2. After being authorized, client obtains a code that it sends to the server
 3. Server (using google.auth.OAuth2) exchanges the code received for an access_token + refresh_token
 4. Server saves these tokens in DB for later re-use
 5. Server can then use the tokens as credentials to instantiate BetaAnalyticsDataClient and make calls

Server-side code to exchange code for tokens (step 3 & 4) :
```
     const { data } = await axios.post(
        'https://accounts.google.com/o/oauth2/token',
        qs.stringify({
          code,
          client_id: appClientId,
          client_secret: appClientSecret,
          redirect_uri: 'http://..............', // from my experience, this should be an authorized callback in Google API Console, but not used here so it doesn't matter which one
          grant_type: 'authorization_code',
        }),
        { headers: { 'Content-Type': 'application/x-www-form-urlencoded', }, }
      );

      // SAVE CREDENTIALS DATA TO DB
```

And to make an API call (step 5) :
```
      // RETRIEVE CREDENTIALS DATA FROM DB

      const oauth2Client = new google.auth.OAuth2(
        this.appClientId,
        this.appClientSecret,
        'http://localhost:3000/admin/connecteurs/oauth2callback'
      );
      oauth2Client.setCredentials(CREDENTIALS DATA);

      // Set OAuth2 client as credentials for Analytics
      const sslCreds = grpc.credentials.createSsl();
      const credentials = grpc.credentials.combineChannelCredentials(
        sslCreds,
        grpc.credentials.createFromGoogleCredential(oauth2Client)
      );
      this.analyticsDataClient = new BetaAnalyticsDataClient({
        sslCreds: credentials,
      });
```

It would definitely be much nicer to have something a bit simple server-side, or better documented (it took me a few days to figure all this out based on the various APIs references.

**Comment by sofisl** [comment]
Hi there! We are migrating this repo to googleapis/google-cloud-node. If this issue still persists, please reopen over there. Thank you!
