### ISSUE TITLE
 PERMISSION_DENIED: User does not have sufficient permissions for this property

### ISSUE THREAD

**Issue by LindaLawton** [googleapis/nodejs-analytics-data#93]
The quick start [quickstart_json_credentials.js](https://github.com/googleapis/nodejs-analytics-data/blob/master/samples/quickstart_json_credentials.js)

Recommends using a serviced account however you have neglected to tell users that they need grant the service account permission to access their data.

Solution:

- Take the service account email address.  either open the json key file or get it from Google cloud console. is the one with a @i n it
- Go to the google analytics web application
- in the admin section for the analytics account you would like the service account to be able to access add it as a user.
- as the analysis data api only reads data it is fine to only grant it read access.

Links to [User does not have sufficient permissions for this property](https://stackoverflow.com/q/67104281/1841839)
Video showing how to grant a user access [User doesn't have any google analytics accounts easy solution](https://youtu.be/s0fwl7tbS8U)

**Comment by sofisl** [comment]
Hi there! We are migrating this repo to googleapis/google-cloud-node. If this issue still persists, please reopen over there. Thank you!
